description = "PRD를 기반으로 핵심 구현 기능 추천 및 스펙 정의"

prompt = """
현재 우리 프로젝트를, spec-kit를 가지고 구현을 시작하려고 함.

현재 코드베이스를 모두 파악해.
docs/prd.md 파일을 참조해.
너무 상상하지말고, 불필요한 옵션을 제거하고, 반드시 필요한 핵심 기능을 위주로 생각해.
반드시 중복되지 않는 Spec으로만 뽑아.
5가지 정도 추천해서 docs/recommendation.md 파일로 작성해줘.
각 추천들의 /speckit.specify 명령어들도 구체적으로 작성해줘.
"""